name: "point-reader"
version: "0926"
save_path: "../ckpt"
train_data_path: "../output/qa_samples.jsonl"
val_data_path: "../output/test.jsonl"
pretrain_model_path: ""

# Trainer
devices: [0, 1]
verbose: True  # 打印保存信息
num_nodes: 1
seed: 42
max_epochs: 2
max_steps: -1
val_check_interval: 1000
check_val_every_n_epoch: 1
gradient_clip_val: 1.0
#
train_batch_size: 6
accumulate_grad_batches: 1
val_batch_size: 2
num_workers: 32
#
max_length: 128
lr: 1e-5

warmup_steps: 1000 
num_training_samples_per_epoch: 30994
save_step: 5000
